version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4040:4040"
    env_file:
      - ./.env
    depends_on:
      - postgres

  postgres:
    image: postgres:13-alpine
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
