version: '3'
services:
  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "4040:4040"
  #   environment:
  #     - DATABASE_HOST=postgres
  #     - DATABASE_PORT=5432
  #     - DATABASE_USER=postgres
  #     - DATABASE_PASSWORD=example
  #     - DATABASE_NAME=mydatabase
  #   depends_on:
  #     - postgres

  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgresUser
      POSTGRES_PASSWORD: postgresPass
      POSTGRES_DB: postgresDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
